"""Naver ncaptcha token refresh client.

The ncaptcha system issues a short-lived token (tokenId) used as the
x-wtm-ncaptcha-token header on pcmap-api GraphQL requests.

The cipherText in the request body is generated by the ncaptcha JavaScript
challenge running in the browser — it cannot be replicated server-side without
executing the JS. This module handles the token exchange once cipherText is
available.
"""

import httpx
from pydantic import BaseModel

NCAPTCHA_TOKEN_URL = "https://ncpt.naver.com/v2/tokens"

_HEADERS = {
    "accept": "*/*",
    "accept-language": "ko,en-US;q=0.9,en;q=0.8",
    "content-type": "text/plain",
    "sec-ch-ua": '"Google Chrome";v="149", "Chromium";v="149", "Not)A;Brand";v="24"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"macOS"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
    "user-agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/149.0.0.0 Safari/537.36"
    ),
}


class NcaptchaTokenRequest(BaseModel):
    cipherText: str
    siteKey: str
    t: str           # challenge metadata (e.g. "1|5|3|133|19")
    referer: str
    origin: str


class NcaptchaTokenResponse(BaseModel):
    tokenId: str


async def fetch_ncaptcha_token(
    request: NcaptchaTokenRequest,
    cookies: dict[str, str],
    q: str,
    tid: str,
) -> NcaptchaTokenResponse:
    """Exchange a browser-generated ncaptcha challenge for a tokenId.

    Args:
        request: Challenge payload produced by the ncaptcha JS in the browser
        cookies: Naver session cookies
        q: Timestamp query param (milliseconds, e.g. str(int(time.time() * 1000)))
        tid: Session tracking ID from the ncaptcha JS

    Returns:
        NcaptchaTokenResponse with tokenId for use as x-wtm-ncaptcha-token header
    """
    headers = {
        **_HEADERS,
        "origin": request.origin,
        "referer": request.referer,
    }
    async with httpx.AsyncClient(headers=headers, cookies=cookies) as client:
        response = await client.post(
            NCAPTCHA_TOKEN_URL,
            params={"q": q, "tid": tid},
            content=request.model_dump_json(),
        )
        response.raise_for_status()
        return NcaptchaTokenResponse.model_validate(response.json())
